### ISSUE TITLE
PHP configuration should not be changed dynamically

### ISSUE THREAD

**Issue by mougrim** [mailru/queue-processor#2]
From [https://insight.sensiolabs.com/projects/e2a071cd-783f-434e-a4ca-8e2f46613a37/analyses/5](https://insight.sensiolabs.com/projects/e2a071cd-783f-434e-a4ca-8e2f46613a37/analyses/5).
Changing PHP configuration dynamically through ini_set() may create hard to debug errors.
The problem is in method `\MailRu\QueueProcessor\Processor\AbstractProcessor::fork()`. Now we can use function `pcntl_get_last_error()`

**Comment by Erliz** [comment]
LGTM
Create pull request 😄
