### ISSUE TITLE
Fix some code analyses issues

### ISSUE THREAD

**Issue by mougrim** [mailru/queue-processor#7]
See report [https://insight.sensiolabs.com/projects/e2a071cd-783f-434e-a4ca-8e2f46613a37/analyses/13](https://insight.sensiolabs.com/projects/e2a071cd-783f-434e-a4ca-8e2f46613a37/analyses/13):
1. remove .idea from .gitignore
2. remove unused \MailRu\QueueProcessor\Processor::$isChild
3. rename \MailRu\QueueProcessor\Util\ArrayUtils::_mergeArray according PSR1 code standard
4. change sleep to usleep src/Processor.php:150

**Comment by Erliz** [comment]
👍
